# Generated by Django 3.0.4 on 2020-03-16 17:21

from django.conf import settings
from django.db import migrations, models
import printutil.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_time', models.DateTimeField(auto_now_add=True)),
                ('source', models.FileField(upload_to='source/')),
                ('username', models.ForeignKey(on_delete=models.SET(printutil.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
