# Generated by Django 3.0.4 on 2020-03-17 09:03

from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('printutil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printrequest',
            name='source',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='source/', verbose_name='Source'),
        ),
    ]
