# Generated by Django 3.0.4 on 2020-03-17 11:38

from django.db import migrations, models
import printutil.models


class Migration(migrations.Migration):

    dependencies = [
        ('printutil', '0004_auto_20200317_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='printrequest',
            name='printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='printrequest',
            name='source',
            field=models.FileField(upload_to=printutil.models.get_file_path, verbose_name='Source'),
        ),
    ]
